import { GameSummaryDTO } from '../api/types';

export const game: GameSummaryDTO = {
  id: '5kxz2',
  team1: {
    id: '4r3ed',
    name: 'Los Angeles Lakers',
    score: 57,
    players: [
      {
        id: '52gd3',
        name: 'Lebron James',
        starter: true,
        number: 23,
        points: 16,
        rebounds: 6,
        assists: 5,
        blocks: 1,
        steals: 2,
        fgm: 5,
        fga: 8,
        ftm: 2,
        fta: 2,
        to: 1,
        three_m: 1,
        three_a: 2,
        fouls: 1,
      },
      {
        id: '32nh7',
        name: 'James Harden',
        starter: true,
        number: 32,
        points: 10,
        rebounds: 3,
        assists: 6,
        blocks: 0,
        steals: 1,
        fgm: 4,
        fga: 8,
        ftm: 2,
        fta: 3,
        to: 1,
        three_m: 1,
        three_a: 2,
        fouls: 1,
      },
      {
        id: 'e4g6k',
        name: 'Stephen Curry',
        starter: true,
        number: 16,
        points: 21,
        rebounds: 4,
        assists: 7,
        blocks: 0,
        steals: 3,
        fgm: 7,
        fga: 9,
        ftm: 3,
        fta: 3,
        to: 1,
        three_m: 1,
        three_a: 2,
        fouls: 1,
      },
      {
        id: 'd1s9o',
        name: 'Rudy Gobert',
        starter: false,
        number: 6,
        points: 9,
        rebounds: 8,
        assists: 1,
        blocks: 3,
        steals: 0,
        fgm: 2,
        fga: 2,
        ftm: 2,
        fta: 4,
        to: 1,
        three_m: 1,
        three_a: 2,
        fouls: 1,
      },
    ],
  },
  team2: {
    id: '7u2ws',
    name: 'Denver Nuggets',
    score: 62,
    players: [
      {
        id: '6ytyh',
        name: 'Paul George',
        starter: true,
        number: 56,
        points: 19,
        rebounds: 6,
        assists: 5,
        blocks: 1,
        steals: 2,
        fgm: 5,
        fga: 8,
        ftm: 2,
        fta: 2,
        to: 1,
        three_m: 1,
        three_a: 2,
        fouls: 1,
      },
      {
        id: '12s3d',
        name: 'Carmelo Anthony',
        starter: true,
        number: 50,
        points: 10,
        rebounds: 5,
        assists: 0,
        blocks: 0,
        steals: 3,
        fgm: 4,
        fga: 8,
        ftm: 2,
        fta: 3,
        to: 1,
        three_m: 1,
        three_a: 2,
        fouls: 1,
      },
      {
        id: 'vb7su',
        name: 'Ja Morrant',
        starter: true,
        number: 69,
        points: 22,
        rebounds: 4,
        assists: 2,
        blocks: 1,
        steals: 2,
        fgm: 6,
        fga: 9,
        ftm: 3,
        fta: 3,
        to: 1,
        three_m: 1,
        three_a: 2,
        fouls: 1,
      },
      {
        id: 'e3w33',
        name: 'Klay Thompson',
        starter: false,
        number: 12,
        points: 2,
        rebounds: 1,
        assists: 1,
        blocks: 0,
        steals: 0,
        fgm: 1,
        fga: 2,
        ftm: 0,
        fta: 0,
        to: 1,
        three_m: 1,
        three_a: 2,
        fouls: 1,
      },
    ],
  },
  tournament: 'Waynesboro 3x3 2023',
  league: null,
  GameFormat: '3v3',
  dateTime: new Date('03/15/23 3:22'),
  periods: 1,
  periodLength: 10,
  GameStatus: 'in-progress',
};
